### ISSUE TITLE
Add system image, please.

### ISSUE THREAD

**Issue by egordorichev** [AndrewAPrice/Perception#1]
Hello! I'm trying to build your OS, but there is no Perception.iso file. Can you ad it, please?

**Comment by rzhikharevich** [comment]
I can be placed in the "Releases" section.

**Comment by egordorichev** [comment]
Yes, I will be cool. Thank you.

**Comment by AndrewAPrice** [comment]
I'm hesitant to share out a disk image until I get something actually fun to play with.
